### ISSUE TITLE
Allow role to be passed in

### ISSUE THREAD

**Issue by laxgoalie392** [CloudSnorkel/cdk-github-runners#123]
We have an existing build role that i would like to reuse. Would be be able to allow that to be passed in and used?

**Comment by kichik** [comment]
For it to be used as the runner role, you'd have to modify the role itself. It would have to gain access to write logs, download images, etc. I think that might be a deal breaker for most use-cases.

You can let the runner assume the role with:

```
const runner = new CodeBuildRunner(stack, 'CodeBuild', {
  label: 'codebuild',
});
const role = aws_iam.Role.fromRoleName(stack, 'Existing Role', 'existing-role-name');
role.grantAssumeRole(runner.grantPrincipal);
```

And then in your code you can:

```
aws sts assume-role --role-arn arn:aws:iam::123456789012:role/existing-role-name --role-session-name github-actions
```

But the far superior way is to use the [aws-actions/configure-aws-credentials](https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions) action. With OIDC you can limit the role assumption to specific repositories and even branches. That way the runner can be shared more easily. Someone created a [CDK construct](https://github.com/aripalo/aws-cdk-github-oidc) for it, but it doesn't seem to support GitHub Enterprise Server (the fingerprints and URL aren't configurable and I assume they are different).

**Comment by laxgoalie392** [comment]
unfortunately, im pretty limited with what i can do with roles assumption / credential assumption at my company. right now we dont use least privileges with our build roles so they have a broad set of policies.

I might just have to add the broad set of policies to this role as well

**Comment by laxgoalie392** [comment]
i can work with adding a policy to the role built in this repo
