### ISSUE TITLE
FargateRunner: missing property to select subnets

### ISSUE THREAD

**Issue by pharindoko** [CloudSnorkel/cdk-github-runners#126]
Hey @kichik,

thanks for this amazing piece of software.
I`m missing the option to set a property "subnetSelection" for the subnets of the fargate runner explicitely.
Is there some intention behind ?

```typescript
   const fargateRunner = new FargateRunner(this, "fargate runner", {
      label: "fargate",
      vpc: existingVpc,
      ...
      ...
      subnetSelection: vpcSubnets,

    });

```

background:

I used this 
```
    const fargateRunner = new FargateRunner(this, "fargate runner", {
      label: "fargate",
      vpc: existingVpc,
      assignPublicIp: false,
      spot: true,
    });

```

and received this error message

```
(node:27784) UnhandledPromiseRejectionWarning: Error: There are no 'Private' subnet groups in this VPC. Available types: Isolated,Deprecated_Isolated
```

br,

flo

**Comment by kichik** [comment]
I believe I initially left it out for simplicity as Fargate seems to have always chosen the right subnet based on `assignPublicIp`. But it can't hurt to have it as an option. I'll add it.

Be careful with isolated subnets as they may not have access to pull from ECR or connect to GitHub.

> thanks for this amazing piece of software.

Thank you! I'm glad you find it useful.
