### ISSUE TITLE
Unrecognized labels cancel entire workflow

### ISSUE THREAD

**Issue by kichik** [CloudSnorkel/cdk-github-runners#133]
From https://github.com/CloudSnorkel/cdk-github-runners/issues/72#issuecomment-1289480905

> In your case it sounds like it's because we expect every job with the `self-hosted` label to also have a label we recognize. It sounds like you have multiple installations of `cdk-github-runners` in different accounts, each implementing different labels. That means some of the installations will not recognize the label and cancel the job. We can probably add a flag to disable this behavior. Let's do this in a separate ticket.

@laxgoalie392

**Comment by laxgoalie392** [comment]
thanks for opening this up!

you're assumptions are correct. I actually have multiple installations in multiple aws accounts (multiple github orgs needing to deploy to multiple aws accounts). i thought the label would appropriately isolate them, but it seems to have caused more of a mess.

**Comment by laxgoalie392** [comment]
i've validated that this fix works for me! you are lightning fast, once again!

**Comment by laxgoalie392** [comment]
@kichik when do you think you will cut another release?

**Comment by kichik** [comment]
I just cut a release for you. I was under the impression you can use my changes without a release so I was waiting for a few more things to make it bigger. I'm curious, how do you test it usually without a release?

**Comment by laxgoalie392** [comment]
thanks! i usually just look at the changes in the PR and apply them manually. not a perfect verification method but quickly does a good enough job i think

**Comment by pharindoko** [comment]
:O thanks @laxgoalie392 - had the same issue - we had pretty weird issues because it even cancelled the jobs for other runners that were not created via this solution ...
