### ISSUE TITLE
feat: add parameters to enable logs on stepfunction

### ISSUE THREAD

**Issue by pharindoko** [CloudSnorkel/cdk-github-runners#148]
hey @kichik,

I would like to have the logs of the step function in cloudwatch to be able to analyze them.

It`s possible to enable the logs (described ![here](https://docs.aws.amazon.com/cdk/api/v1/docs/aws-stepfunctions-readme.html#logging))

...directly in the state machine
https://github.com/CloudSnorkel/cdk-github-runners/blob/2cc54ab5ae4577a4452cec8e753b2326490432b7/src/runner.ts#L285

br,

flo

**Comment by kichik** [comment]
Sounds good to me. We should add a parameter for log retention too with a default of 30 days like the rest. I don't think I will be able to do this in next couple of weeks, so PR would be welcome.

**Comment by pharindoko** [comment]
@kichik  please have a look. I haven`t added any test cases yet.
