### ISSUE TITLE
Best way to scope lambda functions Allowed principals

### ISSUE THREAD

**Issue by diegoaguilar** [CloudSnorkel/cdk-github-runners#174]
### Discussed in https://github.com/CloudSnorkel/cdk-github-runners/discussions/137

<div type='discussions-op-text'>

<sup>Originally posted by **diegoaguilar** October 28, 2022</sup>
I'm deploying hosted runners into an application with some automated policies check. Both setup and webhook handle lambdas are getting flagged because they're pretty open and publicly exposed.

Is there a way to access to these? Should I resolve these from the outputs and then configure? I want to avoid doing a sort of manual check and then getting code to invoke by ARN or something.

Should these even be taken and resolved from the outputs somehow?</div>

## Expectations

Allow the following configurable and selectable setups:

  1. **Default:** Create Lambda URL for the function (simplest zero headache approach)
  2. Disable function access
  3. Create API Gateway for the function that limits access to just GitHub webhook IPs (statically defined in code with action on this project that updates it once in a while, assuming they don't change those IPs often)
  4. Create API Gateway for the function that limits access to a given list of IPs/CIDRs
  5. Nice-to-have: private API Gateway that can only be accessed from certain VPC where GitHub Enterprise is installed

**Comment by diegoaguilar** [comment]
Please @kichik assign this to me

**Comment by diegoaguilar** [comment]
Should _2. Disable function access_ mean, do NOT expose any function from the start?

**Comment by kichik** [comment]
> Should _2. Disable function access_ mean, do NOT expose any function from the start?

Yeah this is specifically useful for the setup function. After initial setup it won't be needed at all for most cases. Best security is to therefore have no access to it at all.

**Comment by diegoaguilar** [comment]
Ok so this is setup function and **NOT** handler function. Naive questions but wanted to make sure
