### ISSUE TITLE
Do not try to delete idle providers if no runner label match 

### ISSUE THREAD

**Issue by moltar** [CloudSnorkel/cdk-github-runners#190]
There was no label match, yet the state machine still waits to reap idle providers. No real harm here, but I think it'd be more optimized if it didn't wait in the cases where there was no match.

In fact, ideally, I think this selection should as early as possible.

<img width="519" alt="screenshot-20221215T163236-pJUkKUi2@2x" src="https://user-images.githubusercontent.com/491247/207916278-650eab5a-c9fa-4d74-9a6a-fcdc3b6fe96b.png">

**Comment by kichik** [comment]
Agreed but I'm not too sure how to implement that yet. If anyone has any ideas, I'm happy to hear or accept PRs for this.

**Comment by kichik** [comment]
Another problem with the current logic is the new retry attempts. Technically the provider can retry for up to an hour. That means the idle runner logic can execute before the runner even started. That means it can get into a situation where it doesn't even delete idle runners.
