### ISSUE TITLE
Use arm instances for dependabot

### ISSUE THREAD

**Issue by pharindoko** [CloudSnorkel/cdk-github-runners#207]
Hey,

I tried to get dependabot version updates on a self-hosted runner using ARM instances (t4g.small) and the default image built by image builder but failed.
It works when I use x64 instances e.g. (t3.small)

![Screenshot 2023-01-05 at 10 27 41](https://user-images.githubusercontent.com/5619511/210773806-5a88ba3f-6d90-4897-a98b-450e0dd3f817.png)

My first **assumption** is that I don`t have the correct architecture for docker using ubuntu arm ...
https://github.com/CloudSnorkel/cdk-github-runners/blob/29708ebe9a83cf84566a7073cda60dd6bbff402a/src/providers/image-builders/linux-components.ts#L144

Can someone confirm or has an idea what could be wrong ?

background: 
We do have a lot of dependabot security and version updates. t4g.small instances are basically for free til end of 2023.

**Comment by pharindoko** [comment]
hmm logged in to ghcr.io to check the images dependabot pulls and inspected them ...

```
docker image inspect ghcr.io/dependabot/dependabot-updater/dependabot-updater@sha256:78200ff10e004dc7c8d06eae2e6962003eeb21a5247e975d1d7fbed0bd765d6d
docker image pull ghcr.io/dependabot/dependabot-updater/dependabot-updater@sha256:78200ff10e004dc7c8d06eae2e6962003eeb21a5247e975d1d7fbed0bd765d6d

docker image inspect ghcr.io/github/dependabot-update-job-proxy/dependabot-update-job-proxy@sha256:21ca670ef8ef375e4168be3e1cedfe1a165724314299e147303cbeae57d6ba3c
docker image pull ghcr.io/github/dependabot-update-job-proxy/dependabot-update-job-proxy@sha256:21ca670ef8ef375e4168be3e1cedfe1a165724314299e147303cbeae57d6ba3c
```

both images have the correct architecture set in the image:

```json
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 3724812126,
        "VirtualSize": 3724812126,
```

**Comment by kichik** [comment]
Are you sure it's the correct architecture? It says `amd64` and not `arm64`. Are those the image hashes you saw the job pull? When you expand "Pulling updater images" from your screenshot, what does it say?

Used container hashes seem to come from:

https://github.com/github/dependabot-action/blob/4a41f80885828d92155bcb3165c594ff019050de/docker/containers.json#L1-L4

I don't see any code that suggests it pulls something different depending on the platform. Sounds like a missing feature in [github/dependabot-action](https://github.com/github/dependabot-action).

**Comment by pharindoko** [comment]
> Are you sure it's the correct architecture? It says `amd64` and not `arm64`. Are those the image hashes you saw the job pull? When you expand "Pulling updater images" from your screenshot, what does it say?
> 
> 
> 
> Used container hashes seem to come from:
> 
> 
> 
> https://github.com/github/dependabot-action/blob/4a41f80885828d92155bcb3165c594ff019050de/docker/containers.json#L1-L4
> 
> 
> 
> I don't see any code that suggests it pulls something different depending on the platform. Sounds like a missing feature in [github/dependabot-action](https://github.com/github/dependabot-action).


Yeah you're right :) my fault...
Mixed arm64 with amd64 - I expected it to be arm64... 

So no runner issue - will close it ... 
thanks for your reply
