### ISSUE TITLE
Image build fails for windows runner

### ISSUE THREAD

**Issue by pharindoko** [CloudSnorkel/cdk-github-runners#212]
Hey,

trying to build an image for windows I do get following error when git should be installed

```shell
Document arn:aws:imagebuilder:eu-central-1:xxxxxx:component/gh-runner-dev-experimental-gh-runner-dev-experimental-windows-builder-git-c7da85e8/1.0.1/1
--
Phase build
Step Run
ExecutePowerShell: STARTED EXECUTION
ExecutePowerShell: Document input parameter: commands
CmdExecution: Command execution has been completed
CmdExecution: [ ERROR ] Command execution has resulted in an error
CmdExecution: Stderr: Invoke-WebRequest : The request was aborted: The connection was closed unexpectedly.At C:\Windows\TEMP\AWSTOE947011157\script-3789370693.ps1:7 char:1+ Invoke-WebRequest -UseBasicParsing -Uri https://github.com/git-for-wi ...+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc    eption    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

```

**Comment by kichik** [comment]
Is this a one time error or is it repeatable? What VPC configuration are you using to run the image builder?

**Comment by pharindoko** [comment]
I've been able to repeat it.

It's the first windows runner I'm trying to create and its based on ec2.

I have all my runners and builders in the same vpc and subnet.

Other windows components like the gh cli and aws cli have been installed as expected.

It occurs when the windows component for git should be installed.

**Comment by kichik** [comment]
Apparently it has been failing to update Windows images on my account too for a while. Trying it out locally shows it tries to download the wrong URL. That doesn't exactly match the error, but I hope fixing the URL will fix the issue. Let me try some things...
