### ISSUE TITLE
Explicitly setting an availability zone for EC2 runners by default

### ISSUE THREAD

**Issue by omichowdhury** [CloudSnorkel/cdk-github-runners#214]
Right now a `subnetId` is always set on the call to `runInstance` which pins the spot request to a specific availability zone.

This leads to the following error

> “We currently do not have sufficient c6a.2xlarge capacity in the Availability Zone you requested (us-east-1a). Our system will be working on provisioning additional capacity. You can currently get c6a.2xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1b, us-east-1c, us-east-1d, us-east-1f

I confirmed that not setting the `subnetId` allows the spot request to be filled by any availability zone

The issue is this line:
https://github.com/CloudSnorkel/cdk-github-runners/blob/c64683b62802de1817e173029a6d9a6695fb5fe9/src/providers/ec2.ts#L246

Before submitting a PR to fix, I wanted to ask what the new behaviour should be.

I was thinking something like:
```ts
this.subnet = props?.subnet ?? props?.vpc?.selectSubnets(props?.subnetSelection).subnets[0]);
```
So that the fallback only applies if you pass in `props.vpc`

Another option would be to have no fallback, so if you use a custom VPC, you have to set a custom subnet explicitly

**Comment by kichik** [comment]
I will respond with more details later, but I believe the main issue was the default VPC. If you don't supply a subnet id, it always uses the default VPC.

**Comment by omichowdhury** [comment]
You're correct that the default VPC gets used, however from that default VPC, the 0th subnet gets selected, which happens to be `us-east-1a`.

For reference here is what our instantiation looks like:
```ts
const runner = new Ec2Runner(stack, 'runner', {
  amiBuilder,
  instanceType: new ec2.InstanceType('c6a.2xlarge'),
  spot: true,
});
```

Which results in this `ec2` Step:
```json
{
  "End": true,
  "Retry": [
    {
      "ErrorEquals": ["Ec2.Ec2Exception"],
      "IntervalSeconds": 60,
      "MaxAttempts": 10,
      "BackoffRate": 1.3
    }
  ],
  "Type": "Task",
  "HeartbeatSeconds": 300,
  "Resource": "arn:aws:states:::aws-sdk:ec2:runInstances.waitForTaskToken",
  "Parameters": {
    "LaunchTemplate": {
      "LaunchTemplateId": "lt-04b19dfb85ed1197a"
    },
    "MinCount": 1,
    "MaxCount": 1,
    "InstanceType": "c6a.2xlarge",
    "UserData.$": "States.Base64Encode(States.Format($.ec2.userdataTemplate, $$.Task.Token, 'dev-ci-services-GithubActionRunners-runnerLogs8574A839-oJ3FuMnJL6Lz', $$.Execution.Name, $.runner.domain, $.owner, $.repo, $.runner.token, 'ec2', '', $$.Execution.Name))",
    "InstanceInitiatedShutdownBehavior": "terminate",
    "IamInstanceProfile": {
      "Arn": "arn:aws:iam::<REDACTED>:instance-profile/dev-ci-services-GithubActionRunners-runnerInstanceProfile4927DB6B-QDp0B6DHVpLe"
    },
    "MetadataOptions": {
      "HttpTokens": "required"
    },
    "SecurityGroupIds": ["sg-07a77348fa3e00aca"],
    "SubnetId": "subnet-0f962af08e2db722b",
    "BlockDeviceMappings": [
      {
        "DeviceName": "/dev/sda1",
        "Ebs": {
          "DeleteOnTermination": true,
          "VolumeSize": 30
        }
      }
    ],
    "InstanceMarketOptions": {
      "MarketType": "spot",
      "SpotOptions": {
        "SpotInstanceType": "one-time"
      }
    }
  }
}
```
Notice that the `SubnetId` gets set. 

We manually changed the step definition to remove this line and confirmed that now runners are appearing in multiple AZs.

**Comment by kichik** [comment]
Oh you're 100% right that this is not ideal. It shouldn't try just one subnet. That's sadly a limitation of the API. I believe the only real solution here would be to try all configured subnets in the step function until one works. I hope `Map` supports `break` somehow otherwise it will be kind of ugly.

My comment about the default VPC was in regards to why this was introduced originally [here](https://github.com/CloudSnorkel/cdk-github-runners/commit/c3aebb123ac341dd6db6edb61f5fa09bef8e9370). Honestly my brain is not working right now so I can't recall the exact reasoning. But either way the solution should just be trying all the subnets.
