### ISSUE TITLE
Delete Idle Runner Wait time not long enough with new EC2 subnet retries

### ISSUE THREAD

**Issue by omichowdhury** [CloudSnorkel/cdk-github-runners#225]
We deployed the latest version and confirmed that the retries on different subnets is working.  Thanks!

We noticed that the Delete Idle Runner step kicks off after 10 minutes, right after the the `runInstances` call finished.
The job it was running got stuck in "waiting for runner".

Increasing the time on the Wait for Delete Idle Runner to 30 mins seems to have fixed things.

Here's the stop function execution run for this:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/969419/213298270-1158737b-6036-4b1f-a2a4-569d35ed1b5d.png">
![image](https://user-images.githubusercontent.com/969419/213298547-1eacca32-a400-47e7-9cf7-bf0965769fc0.png)

**Comment by kichik** [comment]
I wish GitHub had a richer API for self-hosted runners. It could have helped solved so many of these issues. If I just had the start date of the runner, we could calculate that plus 10 minutes, for example.

**Comment by kichik** [comment]
Are you sure Delete Idle Runner caused that issue? It only tries to delete runners that are not busy. GitHub API also fails when trying to delete a busy runner. The attached log shows it tried all that after the runner finished. The runner started an EC2 instance at the 7 second mark the instance was being shut down at the 9:37 mark. The idle runner deletion code kicked in at 10:03. It had nothing to delete. What does the runner log say? I think it ran a job, but not the job you were expecting.

**Comment by omichowdhury** [comment]
I tracked down the runner log and it looks like it did a job. It was the right job, although the logs don't say for which PR it ran on. However looking at Action logs on Github this was the only PR running jobs at the time (it's the middle one):

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/969419/213328797-64891ad3-dfb6-4226-a1a7-9e5b460a2a74.png">
It's marked as green because of a later job that ended up succeeding:


Here's that run in Github:
<img width="1807" alt="image" src="https://user-images.githubusercontent.com/969419/213329685-7708f66f-4bad-4bb2-be9e-b887748392e8.png">

Step function executions:
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/969419/213329830-3d924ec5-04a7-4da0-8569-b472b50ec27c.png">

Runner log groups:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/969419/213327674-e0360e13-c180-4511-9977-586646935287.png">

The runner logs:
```
-----------------------------------------------------------------------------------------------------------------------------------
|       @timestamp        |                                               @message                                                |
|-------------------------|-------------------------------------------------------------------------------------------------------|
| 2023-01-18 13:38:24.154 | --------------------------------------------------------------------------------                      |
| 2023-01-18 13:38:24.154 | |        ____ _ _   _   _       _          _        _   _                      |                      |
| 2023-01-18 13:38:24.154 | |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |                      |
| 2023-01-18 13:38:24.154 | |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |                      |
| 2023-01-18 13:38:24.154 | |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |                      |
| 2023-01-18 13:38:24.154 | |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |                      |
| 2023-01-18 13:38:24.154 | |                                                                              |                      |
| 2023-01-18 13:38:24.154 | |                       Self-hosted runner registration                        |                      |
| 2023-01-18 13:38:24.154 | |                                                                              |                      |
| 2023-01-18 13:38:24.154 | --------------------------------------------------------------------------------                      |
| 2023-01-18 13:38:28.384 | # Authentication                                                                                      |
| 2023-01-18 13:38:28.665 | √ Connected to GitHub                                                                                 |
| 2023-01-18 13:38:29.402 | # Runner Registration                                                                                 |
| 2023-01-18 13:38:33.385 | √ Runner successfully added                                                                           |
| 2023-01-18 13:39:01.761 | √ Runner connection is good                                                                           |
| 2023-01-18 13:39:01.761 | # Runner settings                                                                                     |
| 2023-01-18 13:39:03.014 | √ Settings Saved.                                                                                     |
| 2023-01-18 13:39:03.265 | √ Connected to GitHub                                                                                 |
| 2023-01-18 13:39:03.265 | Current runner version: '2.300.2'                                                                     |
| 2023-01-18 13:39:07.384 | 2023-01-18 13:39:03Z: Listening for Jobs                                                              |
| 2023-01-18 13:39:12.385 | 2023-01-18 13:39:07Z: Running job: base-integration-tests / integration-tests                         |
| 2023-01-18 13:47:02.105 | 2023-01-18 13:47:01Z: Job base-integration-tests / integration-tests completed with result: Succeeded |
| 2023-01-18 13:47:02.105 | √ Removed .credentials                                                                                |
| 2023-01-18 13:47:02.105 | √ Removed .runner                                                                                     |
| 2023-01-18 13:47:02.105 | Runner listener exit with 0 return code, stop the service, no retry needed.                           |
| 2023-01-18 13:47:02.105 | Exiting runner...                                                                                     |
| 2023-01-18 13:47:06.384 | CDKGHA JOB DONE ec2 Succeeded                                                                         |
-----------------------------------------------------------------------------------------------------------------------------------
```

So pretty convinced that the job it ran was for that PR.

Maybe the issue is that for some reason this job completion wasn't report to GH. I was watching the PR build logs and it was stuck on a "Waiting for a runner to claim this job" message (or something to that effect).

**Comment by kichik** [comment]
It really sounds like there are (or just were) some jobs still waiting for a runner from the previous failures due to the previous subnet issue. So every time a new job comes in and a new runner kicks in, the old job gets that runner. As long as you have enough new jobs coming in, you wouldn't notice it. But once there are no more jobs coming in, the last job has no runner.

You can try creating a new step function execution. Just copy the parameters from a previous one on the right repository. Do it until it doesn't find any more hanging jobs. Either that, or go over the repository actions and see if some old ones are still pending.

**Comment by omichowdhury** [comment]
That's possibly it, will keep an eye on it. Thanks for the tip to kick off another instance, would be cool to have a "repair" endpoint or something which can be hit to start off a generic runner to catch up. 

Will close the issue for now

**Comment by kichik** [comment]
I wonder if we can have some function running every hour or so looking for pending jobs that were supposed to be handled and trying again.

**Comment by omichowdhury** [comment]
That would be sweet!
