### ISSUE TITLE
Deprecation notice on CodeBuildImageBuilder.buildImage standard:4.0 for x86 linux

### ISSUE THREAD

**Issue by martinj** [CloudSnorkel/cdk-github-runners#236]
As of 30 Mars, `aws/codebuild/standard:4.0` for x86 linux will be deprecated. 
Can't seem to find and info about this on public facing pages, but the following was informed by email

> Starting March 30, 2023, AWS CodeBuild will be moving these images to an unsupported status and they will not be cached on the build hosts anymore.
> You may continue using these images for your builds, but will notice an increase in provisioning latency after March 30, 2023.

Maybe it would be a good idea to be able to have `buildImage` as option to `CodeBuildImageBuilder`?

**Comment by laxgoalie392** [comment]
I got the same email
