### ISSUE TITLE
Specifying runner architecture

### ISSUE THREAD

**Issue by QuinnyPig** [CloudSnorkel/cdk-github-runners#243]
The docs are a bit unclear on this: how would I specify using an Arm Lambda provider? Feels like it should be an option alongside things like memorySize...

**Comment by kichik** [comment]
You give it an image that was built for ARM64 by specifying an image builder.

https://github.com/CloudSnorkel/cdk-github-runners/blob/main/test/default.integ.ts#L88-L94

The integration test is always a good place to see how most features are used. 

I'll try to think of a better way to convey this in the docs.
