### ISSUE TITLE
feat: use internal load balancer to access configuration page and webhook trigger

### ISSUE THREAD

**Issue by pharindoko** [CloudSnorkel/cdk-github-runners#259]
Why?

lambda function urls are publicly available to the internet and are restricted in our organization on aws organization level by intention to avoid abuse.

As this construct is meant for usage with github enterprise as well it would be great if we can have an additional option to use an internal loadbalancer to invoke the configuration page and webhook handler.

br,

Flo

**Comment by pharindoko** [comment]
hmm 🤔 #231  looks like the same stuff I would like to have ...

**Comment by kichik** [comment]
Yeah that's the idea with #231. @diegoaguilar would you like to chime in?
