### ISSUE TITLE
Lambda runner not resolving with default values

### ISSUE THREAD

**Issue by redbugz** [CloudSnorkel/cdk-github-runners#305]
I'm just starting to try this out, so I followed the instructions to setup on a clean cdk project and did GitHubRunners() with no params and I got some errors.

```
    new GitHubRunners(this, 'runners', {})
```

From the best I can tell, it was complaining that the Lambda imagebuilder couldn't find it's runner files. I see this was recently refactored, and if I changed the contents of the components file I was able to get past this error
It was throwing errors that it couldn't find runner.js, it appears this path perhaps recently change, so I updated the paths in 
https://github.com/CloudSnorkel/cdk-github-runners/blob/main/src/image-builders/components.ts#L509

to look like this and it got further:

```js
            getAssets(_os, _architecture) {
                return [
                    {
                        source: path.join(__dirname, '..', '..', 'assets', 'docker-images', 'lambda', 'linux-x64', 'runner.js'),
                        target: '${LAMBDA_TASK_ROOT}/runner.js',
                    },
                    {
                        source: path.join(__dirname, '..', '..', 'assets', 'docker-images', 'lambda', 'linux-x64', 'runner.sh'),
                        target: '${LAMBDA_TASK_ROOT}/runner.sh',
                    },
                ];
            }
```

Since I don't intend to use the Lambda runners, I just turned them off like this:

```
    new GitHubRunners(this, 'runners', {
      providers: [
        new CodeBuildRunnerProvider(this, 'CodeBuild', {}),
        new FargateRunnerProvider(this, 'Fargate', {}),
      ]
      }),
```

**Comment by kichik** [comment]
Thanks!
