### ISSUE TITLE
feat: use existing vpc-endpoint for private api gateway 

### ISSUE THREAD

**Issue by pharindoko** [CloudSnorkel/cdk-github-runners#320]
Currently it`s only possible to use the ApiGatewayAccess with a new vpc endpoint.
https://github.com/CloudSnorkel/cdk-github-runners/blob/231f8e6a8a790285aa68896fd3b7e5af045e5b3c/src/access.ts#L131

**Issue:**
In our current setup I`m not allowed to create a new vpc endpoint for execute-api. But we do have an existing vpc-endpoint that I can use.

**What I would like to have:**

The possibility to pass an existing vpce-id directly as string property into the ApiGatewayAccessProps that it can be referenced in the resource policy.

**Comment by kichik** [comment]
Are those endpoints properly configured with a security group that you want? We will have to ignore `allowedSecurityGroups` and `allowedIpAddresses` (which we currently ignore due to a bug) with an existing endpoint.
