### ISSUE TITLE
fix: not possible to disable docker installation on image build when windows is used

### ISSUE THREAD

**Issue by pharindoko** [CloudSnorkel/cdk-github-runners#323]
I used this flag to deny the installation of docker for windows workloads due to license cost of docker desktop.
https://github.com/CloudSnorkel/cdk-github-runners/blob/89ba369976f63dd7e937ddfc4e540efa04434a23/src/image-builders/aws-image-builder/deprecated/ami.ts#L119

AmiBuilder is now deprecated and I haven`t found the same functionality yet to disable the docker installation.

**What I would like to have:**

A flag in the imagebuilder to disable the installation of docker similar to how it was done using amiBuilder class...

**Comment by kichik** [comment]
It doesn't use Docker Desktop (which never really worked) anymore:

https://github.com/CloudSnorkel/cdk-github-runners/blob/89ba369976f63dd7e937ddfc4e540efa04434a23/src/image-builders/components.ts#L362-L365

But if you still want to remove it, you can use `removeComponent(RunnerImageComponent.docker())`.

https://github.com/CloudSnorkel/cdk-github-runners/blob/89ba369976f63dd7e937ddfc4e540efa04434a23/test/imagebuilder.test.ts#L200
