### ISSUE TITLE
feat: set custom domain name for apigatewayaccess

### ISSUE THREAD

**Issue by pharindoko** [CloudSnorkel/cdk-github-runners#324]
Hey @kichik,

I currently test the option to use the LambdaAccess.apiGateway option 

```typescript
 new GitHubRunners(this, `${this.stackName}-github-runner`, {
      providers: [githubRunner],
      vpc: existingVpc,
      vpcSubnets: vpcSubnets,
      logOptions: {
        includeExecutionData: true,
        level: stepfunctions.LogLevel.ALL,
        logGroupName: `${this.stackName}-state-machine`,
      },
      allowPublicSubnet: false,
      webhookAccess: LambdaAccess.apiGateway({
        allowedVpcEndpoints: [vpcEndpoint],
      }),
      setupAccess: LambdaAccess.apiGateway({
        allowedVpcEndpoints: [vpcEndpoint],
      }),
      statusAccess: LambdaAccess.apiGateway({
        allowedVpcEndpoints: [vpcEndpoint],
      }),
    });
```
 
In our setup I cannot use the {vpce-id}-{rest-api}.amazon url style as webhook url. I need to use a custom domain name. (I know the root cause ...)

**What I would like to have:**

I need the additional option to set a custom domain name when the apigateway access is used.
https://github.com/CloudSnorkel/cdk-github-runners/blob/89ba369976f63dd7e937ddfc4e540efa04434a23/src/access.ts#L236

e.g. a optional property called customDomains (stringArray) that I can pass into the apiGateway function.

```typescript
 new GitHubRunners(this, `${this.stackName}-github-runner`, {
      providers: [githubRunner],
      vpc: existingVpc,
      vpcSubnets: vpcSubnets,
      logOptions: {
        includeExecutionData: true,
        level: stepfunctions.LogLevel.ALL,
        logGroupName: `${this.stackName}-state-machine`,
      },
      allowPublicSubnet: false,
      webhookAccess: LambdaAccess.apiGateway({
        allowedVpcEndpoints: [vpcEndpoint],
        customDomain: xxx.domain.com
      }),
      setupAccess: LambdaAccess.apiGateway({
        allowedVpcEndpoints: [vpcEndpoint],
      }),
      statusAccess: LambdaAccess.apiGateway({
        allowedVpcEndpoints: [vpcEndpoint],
      }),
    });
```

In the background:
- custom domains will be created
- add a basepathMapping for each custom domain to map the custom domain to the created apigateway.RestApi

**Alternative:**
Add the ability to overwrite the webhook url and return the apigateway as property.
Then I could create the custom domain name and create the api gateway binding on my own.

**Comment by kichik** [comment]
The part I'm not sure about yet here is how to get the Route 53 association working. We need to both return the URL and expose the gateway domain.

**Comment by pharindoko** [comment]
@kichik I create a construct that explains how you can access the private api gateway internally ... https://github.com/pharindoko/cdk-internal-gateway
