### ISSUE TITLE
fix: cannot use apigateway lambdaAccess function with private dns names enabled

### ISSUE THREAD

**Issue by pharindoko** [CloudSnorkel/cdk-github-runners#325]
When you use a private dns name with the vpc endpoint the format for the api url needs to be  
`https://{rest-api-id}-{vpce-id}.execute-api.{region}.amazonaws.com/{stage}`

currently this will be set:
`https://{rest-api-id}.execute-api.{region}.amazonaws.com/{stage}`

https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-api-test-invoke-url.html#apigateway-private-api-route53-alias

**Comment by kichik** [comment]
Is that because you have no private DNS enabled on the endpoint? It worked for me when I tried it with our endpoint.

https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-api-test-invoke-url.html#w37aac15b9c32c26c11
