### ISSUE TITLE
(Re)enable providing custom ASG

### ISSUE THREAD

**Issue by jonathanmorley** [CloudSnorkel/cdk-github-runners#333]
v0.9.7 removed the ability to provide a custom autoscaling group (via a custom capacityProvider) for the `EcsRunnerProvider`.

We have been using this to be able to:
1. Share an ASG between differently sized providers (small/medium/large)
2. Provide our internally-approved AMI to the provider.

While the custom capacityProvider is still available, a new ASG is always created, regardless of whether the capacityProvider in the props already provides one.

**Comment by kichik** [comment]
Should be fixed with 0.10.1. Tested with:

```typescript
new GitHubRunners(stack, 'runners', {
  providers: [
    new EcsRunnerProvider(stack, 'ECS', {
      labels: ['ecs', 'linux', 'x64'],
      vpc,
      capacityProvider: new ecs.AsgCapacityProvider(stack, 'Capacity Provider', {
        autoScalingGroup: new autoscaling.AutoScalingGroup(stack, 'Auto Scaling Group', {
          vpc: vpc,
          instanceType: ec2.InstanceType.of(ec2.InstanceClass.M5, ec2.InstanceSize.LARGE),
          machineImage: ecs.EcsOptimizedImage.amazonLinux2(),
          minCapacity: 1,
          maxCapacity: 3,
        }),
      }),
    }),
  ],
};
```
