### ISSUE TITLE
Investigate `summerwind/actions-runner`

### ISSUE THREAD

**Issue by quad** [CloudSnorkel/cdk-github-runners#355]
The runner images are all manually constructed images. [summerwind/actions-runner](https://hub.docker.com/r/summerwind/actions-runner) about as close to [an official runner image](https://github.com/actions/actions-runner-controller/tree/master/runner) as exists.

**Comment by kichik** [comment]
I don't think we will be able to use the image itself, especially if it's under a non-official owner like `summerwind`. But it did teach me about [hooks](https://github.com/actions/runner/blob/main/docs/adrs/1751-runner-job-hooks.md) which may come useful one day.

The exit hook would be nice if it had access to the job result so we can get rid of the log grepping hack.

We might also be able to simplify the idle reaper by giving it the runner id and actual startup time directly from `.runner`. That said, I don't want to give the runner context permissions to do that as it might get abused by untrusted jobs.

https://github.com/actions/actions-runner-controller/blob/8afef51c8bb4558746eb36fc3f0ad9fd921d0b13/runner/startup.sh#L123-L132
