### ISSUE TITLE
Feature Suggestion: Backstage Plugin

### ISSUE THREAD

**Issue by regicsolutions** [CloudSnorkel/cdk-github-runners#366]
Would be great to have a Backstage plugin where developers are able to manage there runners in a single unified experience. 

Would fit in nicely here as an alternative to gitlab runners: https://github.com/awslabs/app-development-for-backstage-io-on-aws/blob/main/docs/ARCHITECTURE.md#architecture---app-development-for-backstageio-on-aws

**Comment by kichik** [comment]
Do you have a sense of what that would look like? What code is going to change on our side and what is it going to expose? I'm not too familiar with Backstage.io.

**Comment by regicsolutions** [comment]
Backstage is a open-source, single page application that gains its capabilities via plugins which are written in react/typescript. 

There are two powerful out of the box plugins (software catalog and software templates plugin also known as the scaffolder) can get a sneak peek of the software catalog which was aimed to provide developers with a single pane of glass view into a software component - https://demo.backstage.io 

I see this working nicely with the solution aws-labs recently published given the solution only supports gitlab runners. 

backstage-plugins/plugins/scaffolder-backend-module-aws-apps/README.md

**Comment by kichik** [comment]
I don't see how we can easily integrate the aws-labs solution. It doesn't appear to have been written with the intention of being a library or easily reusable code. I am willing to consider PRs for this. It would probably be a good idea to describe a plan here before opening a PR.

**Comment by regicsolutions** [comment]
It's more for reference th
