### ISSUE TITLE
Multiple runners started

### ISSUE THREAD

**Issue by chrisneal** [CloudSnorkel/cdk-github-runners#380]
Hello,

Every action seems to trigger 2 runners (see screenshot of step function executions)...
<img width="1232" alt="image" src="https://github.com/CloudSnorkel/cdk-github-runners/assets/1110269/2043de6b-ad03-4a06-a51e-f3c31411e29e">

Both the step functions are executed with the same input (jobUrl, installationId) etc.

Obviously only 1 of them picks up the job, and then the other one just stays running.

Is this expected behaviour? Or is there an issue somewhere on my end?

Thanks!

**Comment by chrisneal** [comment]
The idle timeout for workers is set to 60 seconds, the second worker (that doesn't pick up the job) will stop after the job that triggered it has ended.

<img width="1578" alt="image" src="https://github.com/CloudSnorkel/cdk-github-runners/assets/1110269/823f199c-ca30-4fe3-91e8-2b8b15790cb9">

**Comment by kichik** [comment]
This is not expected. Can you include the code you're using? Do you see anything unusual on the GitHub side of webhook delivery log?

**Comment by kichik** [comment]
What does GitHub say the results are? Are you sure the job ids are exactly the same (maybe they're just really close in number because they're close in time)?

If I had to guess right now, I'd say it's either a GitHub Actions bug (they have had a bunch of weird outages lately) or maybe your action literally runs twice on accident.

**Comment by chrisneal** [comment]
The jobId's are identical.

<img width="853" alt="image" src="https://github.com/CloudSnorkel/cdk-github-runners/assets/1110269/31a1a091-81c7-45c1-89e2-2d161be46500">

<img width="872" alt="image" src="https://github.com/CloudSnorkel/cdk-github-runners/assets/1110269/fa5a132f-cc0c-4e3b-bbad-71a871a84047">

Any recommendations on ways to possibly fix this? Maybe going through the setup process again (though not sure how to do that)?

**Comment by kichik** [comment]
Does this happen every time?

I don't think redoing the setup process will fix this. But I also don't know why GitHub would send the same queued message twice. So recreating the GitHub app might help.

Maybe one of the other fields of the webhook will have a hint as to why this is happening? Maybe the `sender` field? Is the entire webhook payload exactly the same on both deliveries?

**Comment by chrisneal** [comment]
Yeah, everytime.

In between both of the `workflow_job.queued` events is a single `workflow_job.waiting` event.

The only difference between both of the `workflow_job.queued` payloads is the `deployment.updated_at` field.

I've opened up a Github support case. If I don't hear back from them, I'll go through the setup process again.

Is it as simple as removing the app and then going through the setup process as I did in the first place?

**Comment by kichik** [comment]
That's weird. I wonder what updates the deployment. Maybe another third party app?

> Is it as simple as removing the app and then going through the setup process as I did in the first place?

Basically. You also have to put a new setup secret value to enable the setup again.

**Comment by chrisneal** [comment]
Removing and reinstalling the app didn't help at all unfortunately... Though I have figured out the reasoning for this!

This video explains it:
https://www.youtube.com/watch?v=1c6IQhsB0Zg

Basically because I'm using environments, even though there are no environment rules setup, the workflows still go into the waiting state temporarily before going back into queued again.

Do you think there is a way of checking whether a runner is starting for a specific job before starting another?

**Comment by kichik** [comment]
This is a very frustrating feature. Even if we find a way to deduplicate the input (probably [this](https://medium.com/@shweta2202/step-functions-preventing-duplicate-executions-a4f5f2868381)), the user may not approve the job before the runner times out. That means we really only want to start the runner for the second `queued` event. But there is no way to differentiate between them according to your findings.

**Comment by chrisneal** [comment]
I think this is best way to handle it:

1) When a `queued` webhook event comes in, kick off the step function (as we currently are), then add a wait step (for 10~ seconds). We'll need to dedupe the step function too.

2) After the wait step, hit the Github API to check whether the job is in the `waiting` state. If so, finish. If not, carry on.

Good idea? Bad idea?

**Comment by chrisneal** [comment]
@kichik I think the double queued events must've been an issue with Github, though I think there is still something to look into here. In terms of the waiting step.

**Comment by kichik** [comment]
You mean it stopped happening to you? Because on my [test repo](https://github.com/CloudSnorkel/test/actions/workflows/blank.yml) it still happens:
![image](https://github.com/CloudSnorkel/cdk-github-runners/assets/1156773/46ce0da9-784d-4eee-8a0d-0639bf726482)
> After the wait step, hit the Github API to check whether the job is in the waiting state. If so, finish. If not, carry on.
Combined with deduping, that means waiting for a real approval may prevent the runner from starting as the second queued event will be ignored and the first runner may already have timed-out.

What I have been working on for now is:
1. Use job id in the execution name
2. If runner is still running, using the same name and input will result in no new execution
3. If runner has already timed-out or stopped for any other reason, we will get an `ExecutionAlreadyExists` error
4. If we hit the `ExecutionAlreadyExists` error we modify the input with a counter and retry until we succeed (which may mean we found a runner that's already running or we started a new one)

This way we can minimize any race conditions between checking API and starting runners. The only remaining race condition I can see would be between the second `queued` event and the idle runner reaper. Technically the reaper can stop the runner in the short time between the webhook being received and the runner picking up the job.

**Comment by kichik** [comment]
> Your solution sounds like it'll work well, though we'll still start a runner when it's potentially not necessary (in the case of a real need to wait).

True. I really wish GitHub wouldn't send that extra `queued` event with no way to identify it.

**Comment by chrisneal** [comment]
How about using DynamoDB as a lock? Before the Run Providers step, check against DynamoDB to make sure there isn't already a runner started for the job? If there is, exit. If not, add a key with a lowish TTL to DynamoDB.

**Comment by kichik** [comment]
> How about using DynamoDB as a lock? Before the Run Providers step (after the wait and the API check), check against DynamoDB to make sure there isn't already a runner started for the job? If there is, exit. If not, add a key with a lowish TTL to DynamoDB.
> 
> Edit: This would be in culmination with my suggestion.

I am really trying to avoid that because it can introduce more race conditions and complexity, and may require some kind of Lambda to always run in a loop (we're trying to not run anything unless there are runners active). On the plus side, it will enable us to solve for any unexpected issues by always starting a new runner if one failed to start for whatever reason. We will have the list of jobs that are still queued, and we will be able to count the runners that are there.

**Comment by kichik** [comment]
The payload has something called `statuses_url` which might be useful.
```
{
  "action": "queued",
  "workflow_job": {
    //....
  },
  "deployment": {
//....
    "statuses_url": "https://api.github.com/repos/CloudSnorkel/test/deployments/978938946/statuses",
```

If you go to that URL (no auth required), you get a list of statuses. Each one has a state. The first state is `"waiting"`. The next one is `"queued"`. When the deployment is done, the next one is `"complete"`. We can get that URL and not start a runner for a job that has a deployment that's still `"waiting"`.

This will filter out some double runners. But it will still start two runners if the deployment gets approved before we react to the first webhook.

Is this what you see in your statuses too? Or is there a way where you'd get multiple `"queued"` states there too?

**Comment by chrisneal** [comment]
I don't see multiple `queued` states in the deployment statuses URL. 

What are you thinking the entire flow will be?

**Comment by kichik** [comment]
The entire flow will be replaced by this test. When a webhook with deployment is received, it won't start a runner if the deployment is still `"waiting"`.

**Comment by chrisneal** [comment]
Cool. I've been trying to think whether that could cause any other significant issues, though I think that'll work well. Might still be worth having a wait step though, incase we get and process the webhook before Github moves it into the `waiting` status...

**Comment by kichik** [comment]
I will test out the timing a bit, but I would hope since it's the first status, it shouldn't be a problem.

**Comment by chrisneal** [comment]
They must have some internal change from `queued` to `waiting` but not list it in the statuses. Surely that's got to be a bug.

**Comment by kichik** [comment]
I assume somewhere in their code is something like this flow:

```
const job = new Job(status="queued");
if (environment) {
  const deployment = environment.newDeployment(status="waiting");
  job.setStatus("waiting");
  deployment.wait();
  job.setStatus("queued");
  deployment.setStatus("queued");
}
job.sendToRunner();
job.wait();
if (environment) {
  deployment.setStatus("success");
}
job.setStatus("completed");
```

Instead of starting up the job with:

```
if (environment) {
  const job = new Job(status="waiting");
} else {
  const job = new Job(status="queued");
}
```

Probably some sort of backwards compatibility, but I definitely agree it feels buggy in this context.

**Comment by chrisneal** [comment]
@kichik How's it going with this? Or do you want me to create a PR for the changes?

**Comment by kichik** [comment]
@chrisneal do you have a private repo with deployments enabled? Is the `statuses_url` publicly available there or does it require authentication?

**Comment by chrisneal** [comment]
@kichik Sorry only just noticed you'd replied here, and I hadn't had a chance to do the PR. Yes, I do. Do you still need it?
