### ISSUE TITLE
Feature: Terraform CDK Support

### ISSUE THREAD

**Issue by regicsolutions** [CloudSnorkel/cdk-github-runners#384]
For enterprises that are heavily invested in terraform it would be great if this module supported terraform using the [terraform-cdk](https://github.com/hashicorp/terraform-cdk)

**Comment by kichik** [comment]
CDKtf and CDK don't share the same, or even similar, L2 constructs. I believe this will be a full rewrite. This is not something I want to do at the moment. If someone has an idea on how to make it simple enough so code can be shared, I am open to PRs or forks.

**Comment by regicsolutions** [comment]
A [AwsTerraformAdapter](https://developer.hashicorp.com/terraform/cdktf/create-and-deploy/aws-adapter) was recently introduced to the [terraform-cdk](https://github.com/hashicorp/terraform-cdk) which includes the @cdktf/aws-cdk package and allows you to use Amazon Web Services Cloud Development Kit (AWS CDK) constructs in your CDK for Terraform (CDKTF) projects, wondering if anyone has given this a try?

**Comment by kichik** [comment]
It doesn't support all the resources we use. I also don't see any direct mention of custom resource support, which we use extensively.

**Comment by regicsolutions** [comment]
Got it, thanks for taking the time to look into it
