### ISSUE TITLE
Codebuild imagebuilder can't pull private ECR images

### ISSUE THREAD

**Issue by Bramw2003** [CloudSnorkel/cdk-github-runners#399]
We wan't to use a private docker image for our ECS runners but when trying to deploy this code it fails because codebuild can't pull the image (cross account). Am I missing something? I have the correct IAM and ECR rights setup to pull from the other account.
```typescript
let phpRunnerImage = EcsRunnerProvider.imageBuilder(this, 'EcsPhpRunnerImage', {
    baseDockerImage: 'PRIVATE_IMAGE',
});
```

**Comment by kichik** [comment]
What error are you getting? How are you setting up IAM?

**Comment by kichik** [comment]
Please reopen if you have details.

**Comment by rsanting** [comment]
We are running into this again, I'm not sure if it's exactly similar. But we try to pull an image from an ecr repository in a different account.

So the image lives in ACCOUNT_A and codebuild runs on ACCOUNT_B

This is the iam policy for the ecr repo.

```{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AllowPullFromCI",
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::ACCOUNT_A:root",
          "*",
          "arn:aws:iam::ACCOUNT_B:root"
        ]
      },
      "Action": [
        "ecr:*",
        "ecr:BatchCheckLayerAvailability",
        "ecr:BatchGetImage",
        "ecr:DescribeImages",
        "ecr:DescribeRepositories",
        "ecr:GetDownloadUrlForLayer"
      ]
    }
  ]
}```

This is the error we get:

```ERROR: failed to solve: ACCOUNT_A.dkr.ecr.eu-central-1.amazonaws.com/testing/cake:builder-1: pulling from host ACCOUNT_A.dkr.ecr.eu-central-1.amazonaws.com failed with status code [manifests builder-1]: 401 Unauthorized
' for uniqueId: build```

We thought it might be because of missing `AmazonEC2ContainerRegistryPowerUser` on the codeBuildServiceRole

so we made a fork and added

```    this.role.addManagedPolicy({
      managedPolicyArn: E
        "arn:aws:iam::aws:policy/AmazonC2ContainerRegistryPowerUser"
    });``
i
n src/image-builders/codebuild.ts.

But that also didn't fix it. @kichik If you have any points for us on how to fix this we would love to hear this.

**Comment by kichik** [comment]
If you already have a fork, try duplicating the following line but use the remote account in the new line. 

https://github.com/CloudSnorkel/cdk-github-runners/blob/3de4f799606c04243485afeb19a6bcf8fac9b72a/src/image-builders/codebuild.ts#L311

**Comment by rsanting** [comment]
Yes that works, we only made a fork to test for this issue. Is this something we can fix differently with the current official version? We could also make a pull request, I can imagine trying an ecr login if an image for a different account use was provided. What would be the best way to go about this?
