### ISSUE TITLE
Using a personal access token still requires an installationId

### ISSUE THREAD

**Issue by nicholasgriffintn** [CloudSnorkel/cdk-github-runners#404]
Getting this error on the State Machine after it has been triggered from the GitHub Webhook when using a Personal Access Token (if I manually set it to `-1` it does work to note):

```
States.Runtime in step: Queue Idle Reaper
Cause

1
An error occurred while executing the state 'Queue Idle Reaper' (entered at the event id #2). The JSONPath '$.installationId' specified for the field 'installationId.$' could not be found in the input '{"owner":"<ORG>","repo":"<REPO>","jobId":4442,"jobUrl":"https://github.com/<ORG>/<REPO>/actions/runs/14141441/job/14411","labels":{"self-hosted":true,"linux":true,"codebuild":true}}'
```

The issue appears to be that GitHub isn't sending an `installationId`, I believe it's all set up correctly though, presumably an issue here?: https://github.com/CloudSnorkel/cdk-github-runners/blob/9c1b9d7cdee0af9a0e810ecb9476540b622b6662/src/idle-runner-repear.lambda.ts#L37

**Comment by kichik** [comment]
Does your secret contain `installationId`? If not, try adding it with the value `-1` or `0`. I'll take a look later for a better solution, but that should get you going.

**Comment by kichik** [comment]
I am going to release 0.10.8 with a fix for this. I won't be able to thoroughly test it. It's simple enough, so hopefully it just works. Let me know if it doesn't.

**Comment by nicholasgriffintn** [comment]
> I am going to release 0.10.8 with a fix for this. I won't be able to thoroughly test it. It's simple enough, so hopefully it just works. Let me know if it doesn't.

Thanks! That fixed the issue!
