### ISSUE TITLE
Upgrade to Lambda base image to Node 18.x

### ISSUE THREAD

**Issue by kichik** [CloudSnorkel/cdk-github-runners#425]
See #424

**Comment by sercantor** [comment]
getting this now with actions/checkout@v4

```/tmp/runner/externals/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/runner/externals/node20/bin/node)```

I guess needs another issue to upgrade to node20? :grin: not sure

**Comment by kichik** [comment]
Did checkout@v4 ever work in Lambda? Is this a new issue?

**Comment by sercantor** [comment]
yeah I don't think it was ever working with v4. v3 works though, so idk if it's that important 🤷

**Comment by QuinnyPig** [comment]
@kichik configure-aws-credentials@v4 also expects node20, which throws a GLIBC mismatch error. The base image needs to be something newer I suspect...
