### ISSUE TITLE
0.11.1 Codebuild runner not starting

### ISSUE THREAD

**Issue by chrisneal** [CloudSnorkel/cdk-github-runners#426]
Hey @kichik,

I updated to 0.11.1, and it appears there may be a permission issue.

I've got 2 jobs:
<img width="603" alt="image" src="https://github.com/CloudSnorkel/cdk-github-runners/assets/1110269/89927472-bfb5-424d-856c-29cb7a9e9cb1">

The "Branch Check" runs on a Lambda, and runs correctly. Though the second "Deploy" job, doesn't ever get started.

Looking in the webhook logs it is showing a "Resource not accessible by integration" error while trying to access "https://api.github.com/repos/REMOVED/REMOVED/deployments/1071517142/statuses"

I was upgrading from 0.10.6, and noticed this issue. 

Things I've tried to resolve it:
1) I deleted the app from Github, set a new setup token, and then went through the setup again (incase the token had the wrong permissions).

2) Manually added "Workflows- Read and Write" permissions on the Github app.

Not sure what else I can try.

**Comment by chrisneal** [comment]
Obviously downgrading to 0.11.0 fixes the issue.

**Comment by kichik** [comment]
I think it might be the "deployment" permission? If not that, can you try giving it all permissions, confirming it works, and then removing them by chunks until you find the missing one?
