### ISSUE TITLE
0.11.1 duplicate runner still being created

### ISSUE THREAD

**Issue by chrisneal** [CloudSnorkel/cdk-github-runners#428]
<img width="1959" alt="image" src="https://github.com/CloudSnorkel/cdk-github-runners/assets/1110269/42d9bdc2-07bf-4b50-9669-0f274e8e70cd">

Not sure why this has happened. I'm gonna run some tests, but just FYI.

**Comment by chrisneal** [comment]
No longer able to replicate this. Closing.

**Comment by chrisneal** [comment]
The behavior is inconsistent:
<img width="1730" alt="image" src="https://github.com/CloudSnorkel/cdk-github-runners/assets/1110269/0dddb308-3667-44c0-b2de-21b17ea76126">

As you can see, the first job only created a single runner though the second has duplicate runners.

I think there may be a race condition.

**Comment by kichik** [comment]
The current solution has a built-in race condition. If the deployment is approved before we get a chance to check, then both runners will be started. This can happen if the first webhook gets delayed for whatever reason. GitHub can take a while to send that webhook or we can take a while to process it.
