### ISSUE TITLE
dependabot runner broken using v11

### ISSUE THREAD

**Issue by pharindoko** [CloudSnorkel/cdk-github-runners#432]
I`ve used dependabot runners successfully now for a year with these settings:

```typescript
    const defaultBuilder = Ec2RunnerProvider.imageBuilder(
      this,
      `x64-linux-ubuntu-builder`,
      {
        vpc: existingVpc,
        subnetSelection: vpcSubnets,
        os: Os.LINUX_UBUNTU,
        architecture: Architecture.X86_64,
        logRetention: 7,
        rebuildInterval: Duration.days(7),
        awsImageBuilderOptions: {
          instanceType: ec2.InstanceType.of(
            ec2.InstanceClass.M5,
            ec2.InstanceSize.LARGE,
          ),
        },
      },
    );


    const dependabotRunner = new Ec2RunnerProvider(
      this,
      `${this.stackName}-runner-ec2-dependabot`,
      {
        labels: ["dependabot"],
        vpc: existingVpc,
        subnetSelection: vpcSubnets,
        spot: true,
        instanceType: ec2.InstanceType.of(
          ec2.InstanceClass.T3,
          ec2.InstanceSize.SMALL,
        ),
        amiBuilder: defaultBuilder,
      },
    );
```

with **major release v11** this does not work anymore.

I fixed it with
 
```typescript
labels: ["linux", "dependabot"],
```

The stepfunction finds the correct runner again and starts it up, but this time it fails after registration of the runner in the runner itself.

![image](https://github.com/CloudSnorkel/cdk-github-runners/assets/5619511/b64e695c-e1e6-4817-bc69-5c2dd70376db)

any idea how to analyze or fix this ?

additional info:
Other runners using the same builder and same settings, just different tags - still work as expected.

**Comment by pharindoko** [comment]
Ok this seems to work...

```typescript
labels: ["dependabot", "linux"],
```

**Comment by kichik** [comment]
This was a breaking change in 0.11. The built-in labels will no longer be assumed when choosing a provider. If you want to use `linux` you have to explicitly specify it.

**Comment by pharindoko** [comment]
@kichik 
I know about this breaking 

change. But I did bot expect that the order of the tags ["linux","dependabot"] or ["dependabot","linux"] have an influence on the runner execution for dependabot...
This seems to be the case.

**Comment by kichik** [comment]
That seems to suggest the job itself ran but failed. Do you have any information on why it failed from the job logs?

**Comment by pharindoko** [comment]
No sorry that's all I've found.
No additional debug logs are available in the job itself :-/

**Comment by kichik** [comment]
I have never used dependabot on GHES. If the workflow and its logs are not somewhere in the repo itself, are they maybe on the organization level?

Also, have you been able to consistently reproduce the label order issue? Might have just been a fluke. Maybe the build really did fail because the dependency upgrade was bad.

**Comment by pharindoko** [comment]
I'll try to replicate it.

I've seen in a few different repos that it got stuck...

**Comment by kichik** [comment]
Was this related to the label changes of GHES?

**Comment by pharindoko** [comment]
No, but we can close it - deprecated with 3.9 because here the only label transmitted is 'dependabot'
