### ISSUE TITLE
permissions for repo runner

### ISSUE THREAD

**Issue by pharindoko** [CloudSnorkel/cdk-github-runners#442]
I figured out that the current solution needs to have administration permissions on repository level when I configure the github app for a new repository.

This permissions is way too heavy just for registering runners in a repo and I found multiple github discussions, which propose to have the same permissions settings on repository level available as on organization level available (separate permission to register self-hosted runners).

I don`t see any progress from github side - so my question...
Can we have a feature to register ephemeral runners on organization level ?

**Comment by pharindoko** [comment]
@kichik Sounds good.
So I assume I have your support for this. 🙂 

I checked the code and will add some suggestions here and make a draft PR within the next few days / next 2 weeks.

**Comment by pharindoko** [comment]
Ok - I checked the code.
First thing that needs to be changed is the manifest in the svelte file...
https://github.com/CloudSnorkel/cdk-github-runners/blob/3c7ac100e47cc996f79a66b7e8a083775c554f28/setup/src/App.svelte#L15

@kichik I need your feedback to make a design decision.

### 2 Options how to deal with it.

#### Option1: Radiobutton selection
User can select the RunnerRegistrationLevel on Repository or OrganizationLevel directly in the svelte webapp.
It`s obvious for the user and  in the right context. Maybe later hard to distinguish which level has been chosen on github app creation event. This has to be checked additionally.
Default: `Repository`
Optional: `Organization`

#### Option2: GitHubRunners Property
GitHubRunners properties interface gets a new property (based on enum) to select between Repository | Organization.
This will be injected into the svelte site the same kinda way as the secret arn or token.
(`INSERT_REGISTER_RUNNER_LEVEL_HERE`)
Technically the quite simpler approach. Flag will be set in SSM Parameterstore and can be injected later to the lambda functions to set on which level the runner has to be registered.


Default: `Repository`
Optional: `Organization`

To keep maintainability and have no breaking changes the default value should be `Repository`

**Comment by kichik** [comment]
I would prefer it in setup as that's where all GitHub configuration is currently done. Would be weird to split it up.

We can also consider just always use organization level if user is installing the app on the organization level. But maybe we should wait a bit with that one until issues come up or don't come up with this.

**Comment by pharindoko** [comment]
> I would prefer it in setup as that's where all GitHub configuration is currently done. Would be weird to split it up.
>
fine
 
> We can also consider just always use organization level if user is installing the app on the organization level. But maybe we should wait a bit with that one until issues come up or don't come up with this.
yeah, guess that`s quite easy to change if the rest works as expected.
As you mention this could be a later change...

**Comment by pharindoko** [comment]
hmm I think I waste some time trying to debug the svelte webapp.
Any idea how I can debug this in an easy manner ?
Is it possible via sam-cli to debug lambda functions in a cdk construct ?

**Comment by kichik** [comment]
To locally test the setup page, I use `npx vite` in the `setup` folder. It won't be able to make any HTTP requests, but you can see the UI in action. If you comment out the [domain post](https://github.com/CloudSnorkel/cdk-github-runners/blob/3c7ac100e47cc996f79a66b7e8a083775c554f28/setup/src/App.svelte#L94-L95), you can also see it sending the manifest and see if it's correct. Or you can just `console.log()` the manifest.

It's not perfect, but for such a small "app", it was good enough for me.

**Comment by pharindoko** [comment]
> To locally test the setup page, I use `npx vite` in the `setup` folder. It won't be able to make any HTTP requests, but you can see the UI in action. If you comment out the [domain post](https://github.com/CloudSnorkel/cdk-github-runners/blob/3c7ac100e47cc996f79a66b7e8a083775c554f28/setup/src/App.svelte#L94-L95), you can also see it sending the manifest and see if it's correct. Or you can just `console.log()` the manifest.
> 
> 
> 
> It's not perfect, but for such a small "app", it was good enough for me.

Owright, fine for me too

**Comment by pharindoko** [comment]
These are the tasks that I assume are required:
Secrets.ts
-[ ] Create new secret for runner registration level in cdk

Setup.lambda.ts
-[ ] Add secret arn to setup lambda.ts
-[ ] Determine registrazion level based on permissions for newapp
-[ ] Determine registration level for existing app
-[ ] Update secret value

App.svelte
-[ ] Add parameter to request for existing app

Tokenretriever.lambda.ts
-[ ] Add env variable for registration level / secret arn
-[ ] Add new condition to register token from org (octokit)

Determine runner registration config command for:
-[ ] ec2 (userdata)
-[ ] fargate
-[ ] lambda
-[ ] codebuild
-[ ] ecs

**Comment by kichik** [comment]
Org level runners will also help future "warm pool" runners. It's cheaper to maintain a warm pool of runners when it's for an entire organization rather than repo by repo.
