### ISSUE TITLE
Issue when building Windows Container image

### ISSUE THREAD

**Issue by RichiCoder1** [CloudSnorkel/cdk-github-runners#443]
When building the Windows Container image I'm getting this issue:
```
CmdExecution: Stderr: Enable-WindowsOptionalFeature : The source files could not be found. 
Use the "Source" option to specify the location of the files that are required 
to restore the feature. For more information on specifying a source location, 
see http://go.microsoft.com/fwlink/?LinkId=243077.
At C:\Users\ContainerAdministrator\AppData\Local\Temp\AWSTOE3902723567\script-2
52628507.ps1:15 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName containers -All -N ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature 
   ], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFea 
   tureCommand
 
```

For what research I've done this apparently can be related to Windows not having a network connection, but _every other_ build step is currently passing fine so I'm at a bit of a loss. Especially since I'd really like docker support.

**Comment by kichik** [comment]
Can you include the code you used to get this error? I have weekly builds of all runner images with failure notification. I haven't seen any failures recently so the default config seems to be working.

**Comment by RichiCoder1** [comment]
```
import { Stack } from "sst/constructs";
import { Architecture, EcsRunnerProvider, GitHubRunners, Os, RunnerImageComponent, RunnerVersion } from '@cloudsnorkel/cdk-github-runners';
import { useEnv } from "@***/sst";
import { Duration } from "aws-cdk-lib/core";
import { SubnetSelection, SubnetType } from "aws-cdk-lib/aws-ec2";

export function Runners(this: Stack) {
  const env = useEnv(this, {
    applicationId: "github-runners"
  });
  const { network: { vpc } } = env;

  const subnetSelection: SubnetSelection = {
    subnetType: SubnetType.PUBLIC,
    onePerAz: true,
  };

  new GitHubRunners(this, "Runners", {
    vpc: vpc,
    providers: [
      new EcsRunnerProvider(this, "LinuxEcsProvider", {
        labels: ['company-linux'],
        vpc,
        spot: true,
        subnetSelection,
        imageBuilder: EcsRunnerProvider.imageBuilder(this, "LinuxImageBuilder", {
          vpc
        }),
      }),
      new EcsRunnerProvider(this, "WindowsEcsProvider", {
        labels: ['company-windows'],
        vpc,
        spot: true,
        imageBuilder: EcsRunnerProvider.imageBuilder(this, "WindowsImageBuilder", {
          os: Os.WINDOWS,
          architecture: Architecture.X86_64,
          rebuildInterval: Duration.days(7),
          vpc,
          subnetSelection,
        })
      }),
    ]
  });
}
```

I don't think I'm doing anything weird. I'm convinced something bizzare is happening with the subnets/VPC but I can't figure it out.

**Comment by kichik** [comment]
That's a weird one. As you said, other commands in the same component do succeed downloading files. Specifically the docker installer is downloaded just a few lines above.

The only thing I could think of is that AWS has some invisible proxy for Windows package downloads, just like they have for Ubuntu. Maybe something in your VPC configuration blocks it somehow (NACL?). I would try creating a whole new VPC (temporarily) and seeing if that solves it.

**Comment by kichik** [comment]
@RichiCoder1 any update on this?

**Comment by RichiCoder1** [comment]
I'm afraid I was never able to get to the bottom of this, and ended up taking a different approach. Still baffled at what was breaking. I'm ok closing this!

**Comment by kichik** [comment]
Ok, thanks. Please let me know if you find out more details in the future.
