### ISSUE TITLE
ECS with EC2 getting `No space left on device`

### ISSUE THREAD

**Issue by sercantor** [CloudSnorkel/cdk-github-runners#444]
Hi, here's my situation:

We have black-box tests running "continuously", for stage and prod, and it's using this provider:
```python
        ecs_runner_provider = EcsRunnerProvider(
            self,
            id="EcsRunnerProvider",
            docker_in_docker=False,
            instance_type=InstanceType("t3.medium"),
            max_instances=2,
            cpu=2048,
        )
```

At the end of our action, we have a repository dispatch step, which "chains" another workflow of the same type, so think of it as if we are running two actions continously.

This works fine, the provisioning times are great, and the instances can handle the workload cheaply, but after an hour or two I get this error in the runner's logs

```
Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/_diag/Runner_20231012-152020-utc.log'
```

and here's the full screenshot of the logs.

<img width="1153" alt="resim" src="https://github.com/CloudSnorkel/cdk-github-runners/assets/32751228/1e84580a-6a93-45e3-9f5b-f9e9ab2744ab">

is there anything I'm doing wrong? we are creating tasks, and the tasks pick up instances, I guess the instances don't change, and I'm not sure how we guarantee ephemerality. in normal runner logs, I can see that we remove `.runner` on succesful runs. one thing to note is that in the actions we get our dependencies from cache to run a script. should I add a step where I wipe off disk data? Thanks for any help in advance

**Comment by kichik** [comment]
Bottom line, increase storage on the instance with [storageSize](https://constructs.dev/packages/@cloudsnorkel/cdk-github-runners/v/0.11.3/api/EcsRunnerProviderProps?lang=typescript#property.storageSize). The default is 30GB.
```
        ecs_runner_provider = EcsRunnerProvider(
            self,
            id="EcsRunnerProvider",
            docker_in_docker=False,
            instance_type=InstanceType("t3.medium"),
            max_instances=2,
            cpu=2048,
            storageSize=cdk.Size.gigabytes(200),
        )
```

There are a few things can contribute to data not being immediately cleaned up from previous runs:
1. ECS can take a very long time to clean-up old containers (and their storage). We try to control it by [setting](https://github.com/CloudSnorkel/cdk-github-runners/blob/3c7ac100e47cc996f79a66b7e8a083775c554f28/src/providers/ecs.ts#L514-L515) that timeout to 5 seconds.
2. Docker is technically shared with the runner containers. Images used by the jobs themselves may linger for up to 30 minutes according to [ECS defaults](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/automated_image_cleanup.html). I am honestly not sure if it will clean up all images, or just images ECS itself downloaded.
3. There might something else I haven't considered.
4. Logs that ECS/Docker might keep could be a reason. Issues like this are frequently log related.

If you could use Session Manager to connect to the ECS host and see what takes up most space, that would help pinpoint your specific issue and may help others in the future. You can use `df -h`, `du -sh /*`, `docker images`, and similar commands.

**Comment by sercantor** [comment]
@kichik thanks for the great detailed response, I'll try what you've said and report back. and thanks for explaining the inner workings of things I have little experience with 👏👌

**Comment by sercantor** [comment]
@kichik I'm lingering on this, just switched to fargate for the sake of convenience, closing for now, if I ever need it I'll do more research before opening

**Comment by neehar-pylon** [comment]
@sercantor @kichik While running the fargate provider did you run into any issues using `customImageBuilder`, I added a component for docker but whenever I run a workflow with it on the `Initialize containers` step of my workflow. It is giving me `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?` the following error. Any Ideas ?

**Comment by kichik** [comment]
> @sercantor @kichik While running the fargate provider did you run into any issues using `customImageBuilder`, I added a component for docker but whenever I run a workflow with it on the `Initialize containers` step of my workflow. It is giving me `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?` the following error. Any Ideas ?

Docker is not supported on Fargate. It's an AWS limitation.

**Comment by neehar-pylon** [comment]
`customImageBuilder.addComponent(RunnerImageComponent.docker());` wouldn't this command install docker in the container image ?

**Comment by kichik** [comment]
Docker is not supported even when installed. It can't run.

**Comment by neehar-pylon** [comment]
Is there any other work around if I want to run workflows which requires docker installed ?

**Comment by kichik** [comment]
Use either CodeBuild or EC2. The top of the readme has a table showing which provider supports which features.

Please open a new discussion post for questions in the future.
