### ISSUE TITLE
dependabot runners do not work with GHES version 3.9

### ISSUE THREAD

**Issue by pharindoko** [CloudSnorkel/cdk-github-runners#462]
hey @kichik,

Using dependabot with self-hosted runners broke with cdk-github-runners and GHES version 3.9.

Reason:
self-hosted tag is not transmitted anymore by webhook to the cdk-github-runner solution.

Consequence:
the dependabot job won`t make it to the step function due to this condition, which makes sense.

https://github.com/CloudSnorkel/cdk-github-runners/blob/751f11858011718359e209e85cadd49f2e85390e/src/webhook-handler.lambda.ts#L139

log:
2023-11-10T08:59:15.877Z	114b4b49-bac8-473e-b943-9cb315b3f93a	INFO	Ignoring labels "dependabot", expecting "self-hosted"

I would like to exclude dependabot triggers from the condition, if the dependabot label is transmitted.

**Comment by kichik** [comment]
Do you know if there is a reason they stopped sending that label? Could it be a bug?

**Comment by pharindoko** [comment]
> Do you know if there is a reason they stopped sending that label? Could it be a bug?

I\`ll try to find an answer on that.
I had a look at the webhooks sent out and the label self-hosted won`t be sent anymore.

```json
"labels": [
      "dependabot"
    ],
```

and on the same date the dependabot labeled runner stopped to get executed, we updated from 3.7 to 3.9...

**Comment by pharindoko** [comment]
argh I did not find an issue on this topic.
