### ISSUE TITLE
feat: Enable runnergroup option for provider

### ISSUE THREAD

**Issue by hranum** [CloudSnorkel/cdk-github-runners#500]
First of all, appreciate all the hard work that has been put into this construct.

By default new runners are placed in the default GitHub runner group. 

The option to specify a runner group for a provider upon which the construct uses when it registers the runner with GH, would be a nice addition.

A use case for this is workflow restrictions/security. I'd like some self-hosted runners to only be able to run certain workflow files, which you define in a runner group.

A temporary solution is to define these restrictions in the default runner group, and create a new runner group that don't have these restrictions that "unsafe" actions run on. It will eventually be some extra maintenance to whitelist workflows, since all providers are within the default group.

https://github.com/actions/runner/blob/7310ba0a0825d467f958ab027f0fd99918291721/src/Runner.Listener/Runner.cs#L692

**Comment by kichik** [comment]
For sure. I never played with groups before, but they sound useful based on your description. #472 could also use this, for example.

**Comment by pharindoko** [comment]
> For sure. I never played with groups before, but they sound useful based on your description. @pharindoko in #472 could also use this, for example.

Yeah it`s not the case yet, but this request could come up for us internally as well 👍 
@hranum:
I know you described already the use case but have you thought about a solution or how this could look like based on an easy example.

Do you use it for one or multiple organizations ?
Github Enterprise or Github.com ?
I assume we would have to create the custom runner group for each organization that uses the github app to have a completely automatic way ... what`s your opinion ?

**Comment by pharindoko** [comment]
ok I`ve seen that we could get the  group properties from the webhook queued event:
https://docs.github.com/en/enterprise-server@3.9/webhooks/webhook-events-and-payloads?actionType=queued#workflow_job

runner_group_id integer or null Required
runner_group_name string or null Required

so would it be feasible to add this as an option on provider level ? e.g. 

```typescript
 const myProvider = new CodeBuildRunnerProvider(this, 'codebuild runner', {
   labels: ['my-codebuild'],
   group: 'my-runner-group',
   vpc: vpc,
   securityGroups: [runnerSg],
});
 
```

**Comment by pharindoko** [comment]
@kichik what`s your opinion - do you see any drawbacks ?

**Comment by kichik** [comment]
> ok I`ve seen that we could get the group properties from the webhook queued event:
https://docs.github.com/en/enterprise-server@3.9/webhooks/webhook-events-and-payloads?actionType=queued#workflow_job

That's a good point. We shouldn't spawn the runner unless it's going to match the job. But I'm not 100% sure we should require the workflow to specify the group. On the one hand, being explicit is good. On the other, it somewhat takes away from the automation of groups. If you want to move workflows in/out of a group, you have to update both the group and the workflow.

Do we need to support multiple groups per runner? Can we?

**Comment by pharindoko** [comment]
I`m absolutely happy with the default runner group provided on org level and as it is working now.

Proposal: I would add the group property as an **optional** string array (and support multiple groups per runner would make sense)

1. Would mean we need to read (if available) and match the runner group name property from the webhook with the providers group array (if group property is available) 
2. Attach the corresponding runner group at startup (when the gh runner agent get`s configured.)

```ts
const myProvider = new CodeBuildRunnerProvider(this, 'codebuild runner', {
   labels: ['my-codebuild'],
   group: ['my-runner-group', 'my-second-runner-group']
   vpc: vpc,
   securityGroups: [runnerSg],
}); 
```

```ts
name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on:
      labels: [self-hosted, my-codebuild]
      group: my-second-runner-group
```

**Comment by kichik** [comment]
I'd accept a PR for that. Sounds like it won't break anything.

And I think that behavior will match our current labels behavior. We will only spin up a runner if it can supply all the requested labels by the job. Similarly with this, we will only spin up a runner if it can supply all the requested groups by the job.

And on top of that, the user can set up rules on the GitHub side based on the group.

Did I miss anything?

**Comment by OpenSourceable** [comment]
Any updates on this issue?

**Comment by kichik** [comment]
Turns out I can't try out runner groups because it requires an enterprise account.

> ok I`ve seen that we could get the group properties from the webhook queued event:
> https://docs.github.com/en/enterprise-server@3.9/webhooks/webhook-events-and-payloads?actionType=queued#workflow_job
> 
> runner_group_id integer or null Required
> runner_group_name string or null Required

I believe these are not available for the queued event that we use. Those won't be selected and available until a runner is chosen. Just like `runner_id` and `runner_name`, they will be empty or unavailable.

I am therefore leaning towards a simpler solution where you can specify the group you want the runner to start in. It will have to come with a warning that users can technically cause a bunch of those runners to start by trying to target them from the wrong repos.

```
 const myProvider = new CodeBuildRunnerProvider(this, 'codebuild runner', {
   labels: ['my-codebuild'],
   group: 'my-runner-group',
   vpc: vpc,
   securityGroups: [runnerSg],
});
```

How does that sound to everybody?
