### ISSUE TITLE
Problem Deprecated Construct CodeBuildImageBuilder

### ISSUE THREAD

**Issue by ardaputra94** [CloudSnorkel/cdk-github-runners#556]
Hi i have problem deprecated construct CodeBuildImageBuilder. 

I want to make a CDK to deploy the runner, after I updated cloudsnorkel/cdk-github-runners and aws-cdk-lib to the latest version, I found a Construct problem that has been deprecated. I've read the documentation for the latest version. 
[](url)
https://constructs.dev/packages/@cloudsnorkel/cdk-github-runners/v/0.13.1/api/CodeBuildImageBuilder?lang=typescript

 but still found deprecated

Is the documentation not updated yet ? or is there something wrong with my construct ?

![image](https://github.com/CloudSnorkel/cdk-github-runners/assets/167159587/a9bdd1ad-49c3-4c72-9e78-3eaaa1c879d5)

**Comment by kichik** [comment]
You are looking for `FargateRunnerProvider.newBuilder()`.

**Comment by ardaputra94** [comment]
Hi @kichik. thank you for the reply.

but can't I use the CodeBuildImageBuilder construct ?

**Comment by kichik** [comment]
You can. It's just deprecated. It will be removed with version 1. 

But why would you want to use it? The new one is much easier to use.

**Comment by ardaputra94** [comment]
oke thanks @kichik 

i will try new version

**Comment by ardaputra94** [comment]
Hai @kichik 
sorry i reply again this issue. 

I've looked in the documentation. but didn't find `FargateRunnerProvider.newBuilder()`

Can you show me the documentation that uses `FargateRunnerProvider.newBuilder()`?

thanks

**Comment by kichik** [comment]
Yes, it's `FargateRunnerProvider.imageBuilder()`. I got it wrong in the first comment.
