### ISSUE TITLE
Add Environment Variable

### ISSUE THREAD

**Issue by ardaputra94** [CloudSnorkel/cdk-github-runners#557]
Hai i have problem 

`Received response status [FAILED] from custom resource. Message returned: EnvironmentVariable value cannot be null`

How to add Environment Variable ?

Thanks

**Comment by kichik** [comment]
Can you please share some code to reproduce this?

**Comment by ardaputra94** [comment]
hai @kichik 

this is my code


  ```
  const myBuilderArm = FargateRunnerProvider.imageBuilder(this, 'MyBuildArm', {
        architecture: Architecture.ARM64,
        os: Os.LINUX_UBUNTU,
        vpc: vpc
     })
  
    const codeBuildarm64 = new FargateRunnerProvider(this, 'CodeBuildARM64',{
        labels: ['codebuildarm64'],
        imageBuilder: myBuilderArm
    }); 


    new GitHubRunners(this, 'runners', {
      providers: [codeBuildarm64],
    });
```

**Comment by kichik** [comment]
I am unable to reproduce your issue with the code provided. Please include fuller log and version information.

You may also be interested in this discussion #509.

**Comment by ardaputra94** [comment]
this is the only log that is in cloudformation
`Received response status [FAILED] from custom resource. Message returned: EnvironmentVariable value cannot be null`

my version 0.13.1

does it require adding the add env variable ?

**Comment by kichik** [comment]
That doesn't seem like a complete log. Where is that from?

**Comment by ardaputra94** [comment]
when i deploy my cdk. and then i check event in cloudformation..

i try again deploy cdk in local. this is the error I got

**Comment by kichik** [comment]
Please attach the complete output of the CDK command.

**Comment by kichik** [comment]
Please reopen if you have more details.
