### ISSUE TITLE
Windows runner: no logs / no access

### ISSUE THREAD

**Issue by pharindoko** [CloudSnorkel/cdk-github-runners#564]
Hey,

I need to debug some windows runners, but I`m not able to.
this only occurs for windows runners not for linux runners.

The cloudwatch agent has been successfully baked into the windows runner image as expected.

- Cannot connect via ssm to the instance to get a powershell terminal
- No logs are written to the  appropriate log group (checked the group again via status.json file)

**Comment by kichik** [comment]
My Windows runners have logs and I am able to SSM connect. So it sounds like it might be a VPC issue. Maybe they're running in an isolated VPC with no SSM or CloudWatch endpoint?

**Comment by pharindoko** [comment]
Hmm I have them in the same vpc together with the linux runners. On linux everything works fine ... argh ...

**Comment by kichik** [comment]
I take it back. It worked on May 9th, but today it's not working. The AMI for today was built on May 11th. So maybe there is an issue there with some upstream package.

**Comment by pharindoko** [comment]
Thanks @kichik !

**Comment by pharindoko** [comment]
btw - works as expected
