### ISSUE TITLE
feat: add private registry mirror

### ISSUE THREAD

**Issue by QuanticPotatoes** [CloudSnorkel/cdk-github-runners#569]
Hi !

I wanted to add a registry mirror on the github runner but i couldn't find any options or documentation to do it.
I found on the codebase of the project the `dindCommand` :
```ts
dindCommand = 'nohup sudo dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 & '
```
So i patched the package to add my registry :
```ts
dindCommand = 'nohup sudo dockerd --host=unix:///var/run/docker.sock --registry-mirror=https://registry.foo.com --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 & '
```
I don't know if an option was available, if it's not the case. It would be great to be able to add a property on the runnerProvider. What do you think 😄 ?

**Comment by kichik** [comment]
Since this can be set in the [configuration file](https://docs.docker.com/docker-hub/mirror/#configure-the-docker-daemon) as well, building your own runner image with this might do the trick.

Something like:

```typescript
const myBuilder = FargateRunnerProvider.imageBuilder(this, 'image builder');
myBuilder.addComponent(
  RunnerImageComponent.custom({
    commands: [`echo '{"registry-mirrors": ["https://<my-docker-mirror-host>"]}' > /etc/docker/daemon.json'],
  }),
);

const myProvider = new FargateRunnerProvider(this, 'fargate runner', {
   labels: ['customized-fargate'],
   imageBuilder: myBuilder,
});

// create the runner infrastructure
new GitHubRunners(this, 'runners', {
   providers: [myProvider],
});
```

**Comment by kichik** [comment]
Please re-open if the proposed solution doesn't work.

**Comment by QuanticPotatoes** [comment]
Hi @kichik !
Thanks for the answer, i will try it out 👍 . It's a far better solution than patching the package 😂 (it fell a bit dirty to do that).
It would be great that the custom component was integrated as a generic RunnerImageComponent on the repo.
Our company triggers many CI per day, it's was a pain in the *** when we hit the docker pull limit 😅
