### ISSUE TITLE
Cancel prev jobs when new commit has arrived in PR

### ISSUE THREAD

**Issue by nkhine** [CloudSnorkel/cdk-github-runners#579]
Hello,
Is there a way to cancel  job when a new commit has been pushed?

For example in GitHub actions you have the `cancel-in-progress` flag https://docs.github.com/en/enterprise-cloud@latest/actions/using-jobs/using-concurrency#example-using-concurrency-and-the-default-behavior

Is this available or is it logic we would have to build?

**Comment by kichik** [comment]
I think `cancel-in-progress` should just work. Let me know if it doesn't.

**Comment by pharindoko** [comment]
Yes, works. We use it in a lot of workflows.
