### ISSUE TITLE
[WARNING] aws-cdk-lib.aws_lambda.FunctionOptions#logFormat is deprecated

### ISSUE THREAD

**Issue by wash-amzn** [CloudSnorkel/cdk-github-runners#596]
The CDK warns about the construct's use of a deprecated property. No indication of when this will actually start breaking, probably not for a while.
```
[WARNING] aws-cdk-lib.aws_lambda.FunctionOptions#logFormat is deprecated.
  Use `loggingFormat` as a property instead.
  This API will be removed in the next major release.
```

**Comment by kichik** [comment]
They never break until a major release. So it will break for CDK v3. This issue keeps repeating because we try to keep our support of older CDK versions. 

Anyway, #623 fixes this and version 0.14.4 will have it.
