### ISSUE TITLE
Web-based interface to automatically setup GitHub app

### ISSUE THREAD

**Issue by kichik** [CloudSnorkel/cdk-github-runners#6]
We can create [GitHub App from manifest](https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app-from-a-manifest). It doesn't include client id and secret, but are those truly required? Can we use API to generate them? It also doesn't install the app, but there is probably a way to direct the user to the right URL automatically. We can then collect the installation webhook event and save installation id from there.

There are security considerations with this. We definitely don't want to let anyone who can guess the URL attach itself to our service. But we want to keep it simple so authentication against Cognito or IdP is a bit too much. Maybe we can settle for a one time setup token that gets deleted once the installation is complete. It can be given to the user in the stack output or with another function like the status function.

**Comment by moltar** [comment]
Might be helpful https://github.com/jogold/cloudstructs/tree/master/src/slack-app

**Comment by kichik** [comment]
> Might be helpful https://github.com/jogold/cloudstructs/tree/master/src/slack-app

Thanks! I'll take a look.
