### ISSUE TITLE
ECS: Support Amazon Linux 2

### ISSUE THREAD

**Issue by choco-nishant** [CloudSnorkel/cdk-github-runners#622]
After [this](https://github.com/CloudSnorkel/cdk-github-runners/pull/532) release we are not able to use Amazon Linux 2. Some of our tools rely on legacy features which was present in AL2. Is there a workaround ? It would be nice if we can choose the image type

**Comment by kichik** [comment]
That PR should have fixed AL2. Can you add more details on what exactly isn't working? You should already be able to choose the image type with something like:

```
EcsRunnerProvider.imageBuilder(stack, 'ECS builder', {
  os: Os.LINUX_AMAZON_2,
})
```

**Comment by choco-nishant** [comment]
I tried using `Os.LINUX_AMAZON_2` but its still deploying the amazon-linux-2023 for both X86_64 and arm64. I guess its due to [this](https://github.com/CloudSnorkel/cdk-github-runners/pull/532/files#diff-5684cdf134f78e857174db494464c88bf44a7898cc3a35c93ee17c42e08a1133R470) change

```
[~] AWS::EC2::LaunchTemplate arm4vcpu/Launch Template arm4vcpuLaunchTemplateA0060405 
 ├─ [~] LaunchTemplateData
 │   ├─ [~] .ImageId:
 │   │   ├─ [-] resolve:ssm:/aws/service/ecs/optimized-ami/amazon-linux-2/arm64/recommended/image_id
 │   │   └─ [+] resolve:ssm:/aws/service/ecs/optimized-ami/amazon-linux-2023/arm64/recommended/image_id
 │   └─ [~] .TagSpecifications:
 │       └─ @@ -3,6 +3,10 @@
 │          [ ] "ResourceType": "instance",
 │          [ ] "Tags": [
```

**Comment by kichik** [comment]
But that's for the ECS instance, not the containers running in it. Jobs don't run directly on that. Why does the instance matter? What do you have running there and how?

Either way, you should be able to override it by passing your own capacity provider. Property override will work too.

**Comment by choco-nishant** [comment]
some of our tool which runs on github action requires cgroupv1 and AL2023 supports cgroupv2. When we updated to latest version of this library, some tools started failing due cgroupv2. Ideally it should be backward compatible. 

But I will try to override this property as well. Thanks!
