### ISSUE TITLE
Managed Image

### ISSUE THREAD

**Issue by tsuga** [CloudSnorkel/cdk-github-runners#628]
Is it possible to specify a managed image (e.g. `aws/codebuild/standard:7:0`) for CodeBuild provider so that additional resources such as ECR and Lambda are not required?

**Comment by kichik** [comment]
The base image doesn't have everything we need. Specifically the [actions runner](https://github.com/actions/runner) is not installed. That said, you can use [`StaticRunnerImage.fromDockerHub`](https://constructs.dev/packages/@cloudsnorkel/cdk-github-runners/v/0.14.4/api/StaticRunnerImage?lang=typescript#fromDockerHub) or similar implementation to avoid ECR. You will need to somehow install the actions runner too. I would imagine it's not worth the effort. 

Lambda on the other hand is more of a hard requirement. It's used to handle the webhook and lifecycle of the runner. 

Can I ask why you're trying to get rid of these dependencies?

**Comment by tsuga** [comment]
It looks like, at least the default image of CodeBuild runner is shipped with GH actions runner.
Generally speaking, I value less resources to avoid any potential problem.

**Comment by kichik** [comment]
Sounds like they may have added that for their support of [GitHub Actions](https://docs.aws.amazon.com/codebuild/latest/userguide/action-runner.html). Honestly it sounds like that feature might be more in line with what you're looking for.

I also value less resources, but it sounds like you value it even more. That said:
* Customizable runner image that remains up-to-date is one of the core differentiators of this project.
* We try to use fine granular permissions wherever possible so new resources are harder to abuse.
* We take great care to cleanup after ourselves on both stack deletion and during normal usage. That should help keep clutter down.
