### ISSUE TITLE
Cross Request Job Stealing 

### ISSUE THREAD

**Issue by ismailcool5152** [CloudSnorkel/cdk-github-runners#645]
Hi Guys, 

we are setting up the runners for the Github enterprise and it seem , when more than 2/3 repos creates pull/Merge request , the Fargate job or lambda job created for one repo execute task for another Git repo. 

Example :- 
Repo 1 :- Created a Pull request :- State Machine Shows the Request Completed . 
Github workflow is still waiting for the job to be picked up

Repo 2:- Create a pull Request :- State machine shows request completed 
Github job completed

**Comment by kichik** [comment]
The runners can pick up jobs from any repo as long as the labels match. But it should start enough runners to cover all jobs. 

Did you see marching number of jobs and state machine executions? Does the webhook log have any errors? Do you maybe have some label overlap?

**Comment by ismailcool5152** [comment]
so , we have jobs defined centrally. Like PR Review and Merge Build jobs. 

So any repo creating a PR, they will use the same Job PR Review and then it will have the same label like (PR Review Task). 
So yes , there is an overlapping . 

But no errors in the State Machine execution .

**Comment by kichik** [comment]
What about the webhook log on GitHub side and webhook handler log on our side? You should be able to see if the expected events are received and processed with both of those. 

Could you also include some details about your provider, labels and workflow setup?

**Comment by ismailcool5152** [comment]
It looks like, the problem is, there were some events which were not able to be converted to the State Execution. 

Reason , state execution needs a name and limit is 80 char (Runner generates 60 char name) 

This is how runner generates the state exec name :- 
git org name + git repo name + Random string . 

if git org name + git repo name > 60 char . random string is not generated and then State Exec can not start as it will be duplicate .

So eventually we are planning to shorten the Repo name to make sure there is some room for random charachters .

**Comment by kichik** [comment]
That's weird. We have code to trim the execution id to size. I'll have to take a deeper look into it.

**Comment by kichik** [comment]
Would you be able to share more details? Perhaps even an example of the execution name that was duplicate? The code already limits the number of characters it takes from the org/repo name to 50 to leave hopefully enough room for a lot of random characters.

https://github.com/CloudSnorkel/cdk-github-runners/blob/391974253a3f119dcbe4ca95636c90356461046b/src/webhook-handler.lambda.ts#L179-L181

**Comment by ismailcool5152** [comment]
No , in our case , it did not truncate :/ ... The way it is doing is , StateExecName = git_org_name + git_repo_name + Random Numbers. 

I guess , you can just flip this equation to reverse  ?

**Comment by kichik** [comment]
Are you sure you're using the latest version? This was fixed with #555 in [version 0.13.1](https://github.com/CloudSnorkel/cdk-github-runners/releases?q=555&expanded=true).

**Comment by ismailcool5152** [comment]
Dang , we are stuck on this version it seems "0.12.5"

**Comment by kichik** [comment]
Phew... You had me really worried there 😄
