### ISSUE TITLE
Upgrade Instructions

### ISSUE THREAD

**Issue by QuinnyPig** [CloudSnorkel/cdk-github-runners#78]
What's the "golden path" to upgrade the version of the runner contained within the Docker image (specifically for Lambda, but across the board I suppose)? GitHub is whining about it being outdated on Action invocation...

**Comment by kichik** [comment]
The latest version updates the Docker image every week by default. You can specify a different [rebuildInterval](https://constructs.dev/packages/@cloudsnorkel/cdk-github-runners/v/0.3.1/api/CodeBuildImageBuilderProps?lang=typescript#property.rebuildInterval) with a custom image builder, if you want.

If you need to trigger a new build right now, find the CodeBuild project in charge of the image build and trigger it. No parameters are needed. Its description should be something like:

> Build docker image for self-hosted GitHub runner github-runners-test/Lambda Image Builder x64 (Linux/X86_64)

If you want to stick with the old version that doesn't update automatically, a re-deploy with a cleaned-out `cdk.out` folder should do it.

**Comment by QuinnyPig** [comment]
Ah, upgrading to current from 0.10.0 sorted it; thanks.
